# Generated by Django 3.2 on 2021-05-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
